In [2]:
import torch
import torch.nn as nn
import math
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, dataloader

In [3]:
torch.tensor(10)

tensor(10)

In [4]:
d_model = 512
torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [5]:
torch.arange(0, d_model, 2).float()

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [6]:
torch.arange(1, d_model, 2).float()

tensor([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,
         25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,
         49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,
         73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,
         97.,  99., 101., 103., 105., 107., 109., 111., 113., 115., 117., 119.,
        121., 123., 125., 127., 129., 131., 133., 135., 137., 139., 141., 143.,
        145., 147., 149., 151., 153., 155., 157., 159., 161., 163., 165., 167.,
        169., 171., 173., 175., 177., 179., 181., 183., 185., 187., 189., 191.,
        193., 195., 197., 199., 201., 203., 205., 207., 209., 211., 213., 215.,
        217., 219., 221., 223., 225., 227., 229., 231., 233., 235., 237., 239.,
        241., 243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
        265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285., 287.,
        289., 291., 293., 295., 297., 29

In [7]:
d_model = 512

# Using torch.exp
exp_values = torch.exp(torch.arange(0, d_model, 2).float() * (math.log(10000.0) / d_model))

# Using torch.pow
pow_values = torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

# Check if both are the same
print(torch.allclose(exp_values, pow_values))  # Should be True


True


In [8]:
512 // 64

8

In [9]:
512/64

8.0

### Mask in Transfomer

Pad mask

In [10]:
atten_scores = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]]).float()

pad_mask = torch.tensor([[1, 1, 1, 0],
                         [1, 1, 0, 0]])
atten_scores.masked_fill(pad_mask == 0, float('-inf'))

tensor([[1., 2., 3., -inf],
        [5., 6., -inf, -inf]])

the mask change the value in unwanted position to -inf, the value will become 0 after passing softmax

Causal mask

In [11]:
seq_len = 5
# diagonal = 0 : default
# diagonal > 0 (up to length) : shift to upper
# diagonal < 0 (up to length) : shift to lower
# diagonal: the step toward up/down 
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1) # torch.tril is lower triangular matrix
causal_mask

tensor([[[0., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0.]]])

In [12]:
# False: allow attention
# True: Masked(prevent future access)
causal_mask.bool()


tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [13]:
(causal_mask == 0).type(torch.int)

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

### $W_q \times Q$

In [14]:
batch_size = 2
seq_len = 5
d_model = 8  # Model embedding size
h = 2
d_k = d_model // h
q = torch.randn(batch_size, seq_len, d_model)
k = torch.randn(batch_size, seq_len, d_model)
v = torch.randn(batch_size, seq_len, d_model)

w_q = nn.Linear(d_model, d_model)
w_k = nn.Linear(d_model, d_model)
w_v = nn.Linear(d_model, d_model)

In [15]:
w_q

Linear(in_features=8, out_features=8, bias=True)

In [16]:
w_q.weight

Parameter containing:
tensor([[ 7.5591e-04,  4.4857e-02,  1.4582e-01, -2.1877e-01,  2.1747e-01,
          1.8150e-01,  1.5741e-01,  1.2602e-01],
        [ 8.8719e-02,  2.7200e-01, -3.4544e-01,  2.0090e-01, -4.4764e-02,
         -1.2815e-01,  9.3956e-02,  4.8173e-02],
        [-9.1833e-02,  1.2522e-01, -4.3306e-02, -1.2683e-01, -3.0004e-01,
         -1.1195e-01,  3.2550e-01,  1.8483e-01],
        [-5.9201e-02, -2.5787e-01,  3.4349e-01,  1.7445e-01, -2.5080e-01,
          1.5355e-01, -2.4857e-01,  3.5176e-01],
        [ 2.2605e-01, -3.2244e-01, -8.4742e-02,  1.2366e-01, -9.5108e-02,
          1.1743e-01,  4.7694e-02, -1.7589e-02],
        [ 1.6352e-01, -1.0181e-01, -1.1778e-01,  1.7568e-01, -9.2812e-02,
         -3.7827e-02, -3.1650e-01, -1.3969e-02],
        [ 7.6046e-03, -1.2586e-04,  2.7877e-01,  5.8528e-02,  2.0851e-01,
         -2.6827e-01, -2.3720e-01, -1.8464e-01],
        [-2.3086e-01, -3.0483e-02, -1.3578e-01, -1.4407e-01, -9.5851e-02,
          2.1293e-02,  2.3807e-01, -2.4179e

In [17]:
w_q.bias

Parameter containing:
tensor([-0.3400, -0.3509,  0.2995, -0.1715, -0.2445,  0.1943, -0.3062, -0.2653],
       requires_grad=True)

In [18]:
q

tensor([[[-0.1758, -0.7158, -1.6454, -0.1701, -0.8235, -1.9992, -1.5552,
           1.5420],
         [ 0.9165,  1.1402, -0.0271,  0.8261,  0.9398, -0.9483,  0.0492,
          -0.5483],
         [ 1.2590,  1.5621, -1.3211,  0.0960,  1.5383, -0.6539, -0.0911,
           0.9099],
         [ 0.2910,  0.2309, -0.4954, -1.0792,  0.6189,  0.4962,  0.2605,
           0.2538],
         [-0.5783,  0.8073,  0.2560, -0.2330,  0.3843,  0.0537, -0.2927,
           1.6973]],

        [[-2.1391,  0.2016,  0.3085,  0.7132,  1.4065,  0.4722,  1.1029,
          -0.2255],
         [-1.4241,  0.9203, -0.1398,  0.7591,  1.3070,  1.6616, -0.2865,
          -1.0090],
         [-0.1426, -1.0962,  0.9393,  0.1482,  1.9969, -1.2529, -0.0523,
          -0.0634],
         [-0.9436,  1.5869, -0.7038, -0.2044,  0.4028, -0.9870,  0.8727,
          -1.8494],
         [ 0.8823, -0.6066,  1.8098, -0.2472,  0.3164, -0.4205,  0.5744,
           0.3119]]])

In [19]:
w_q(q)

tensor([[[-1.1674,  0.1943,  0.5684,  0.2572, -0.1927,  1.0251, -0.3273,
          -0.6617],
         [-0.5020,  0.2736, -0.0067, -0.9714, -0.4892,  0.3171,  0.2813,
          -0.5930],
         [-0.1665,  0.7116,  0.1747, -1.2294, -0.5832,  0.3117, -0.3098,
          -0.8411],
         [ 0.1320, -0.3626,  0.3505, -0.6611, -0.3372, -0.0751, -0.6180,
          -0.1649],
         [ 0.0452, -0.2877,  0.5693,  0.2835, -0.7601, -0.0223, -0.4313,
          -0.6734]],

        [[ 0.0931, -0.4798,  0.2598, -0.5001, -0.7527, -0.5814, -0.2482,
           0.2701],
         [-0.0728, -0.3731, -0.4027, -0.5964, -0.6825, -0.0618, -0.2307,
           0.0309],
         [-0.0941, -0.8932, -0.3718, -0.2343, -0.3230,  0.0775,  0.7399,
          -0.5631],
         [-0.5147,  0.3004,  0.5731, -1.9222, -1.0152, -0.3250, -0.0385,
           0.6244],
         [ 0.0736, -1.0037,  0.2922,  0.3342, -0.0909, -0.0559,  0.1755,
          -0.6386]]], grad_fn=<ViewBackward0>)

In [20]:
# w_q(q) equals to q * w_q.wieght + bias
assert torch.allclose(w_q(q), torch.matmul(q, w_q.weight.T) + w_q.bias), "w_q(q) doesn't equl to q*w_q^T + bias"

In [21]:
# assert torch.allclose(w_q(q), q @ w_q.weight.T), 'they are different'

In [ ]:
# If w = nn.Linear(d_model, d_model, bias=False) then they will be the same
w_test = nn.Linear(d_model, d_model, bias=False)
assert torch.allclose(w_test(q), q @ w_test.weight.T), 'they are different'

# q @ w_q^T, @ is matrix multiplication

In [23]:
query = w_q(q)
key = w_k(k)
value = w_v(v)
query.shape

torch.Size([2, 5, 8])

In [24]:
# keep the batch size and seq_len, decompose the matrix into smaller matrix
# so we can give each small matrix different head
# later, we can perform independent attention calculations for each head
query.view(query.shape[0], query.shape[1], h, d_k).shape

torch.Size([2, 5, 2, 4])

In [25]:
"""
The reason for using (batch_size, h, seq_len, d_k) instead of (batch_size, seq_len, h, d_k) is that:

The attention mechanism operates independently across heads.
Each head will perform self-attention on its own set of d_k-dimensional vectors.
The typical implementation of multi-head attention expects the shape (batch_size, h, seq_len, d_k).
When performing matrix multiplications (like query @ key.T), we want to apply attention per head.
This format is easier for batched computations in PyTorch and TensorFlow.
"""

query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2).shape

torch.Size([2, 2, 5, 4])

In [26]:
query = query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2)
key = key.view(key.shape[0], key.shape[1], h, d_k).transpose(1, 2)
value = value.view(value.shape[0], value.shape[1], h, d_k).transpose(1, 2)


In [27]:
query.transpose(-2, -1)

tensor([[[[-1.1674, -0.5020, -0.1665,  0.1320,  0.0452],
          [ 0.1943,  0.2736,  0.7116, -0.3626, -0.2877],
          [ 0.5684, -0.0067,  0.1747,  0.3505,  0.5693],
          [ 0.2572, -0.9714, -1.2294, -0.6611,  0.2835]],

         [[-0.1927, -0.4892, -0.5832, -0.3372, -0.7601],
          [ 1.0251,  0.3171,  0.3117, -0.0751, -0.0223],
          [-0.3273,  0.2813, -0.3098, -0.6180, -0.4313],
          [-0.6617, -0.5930, -0.8411, -0.1649, -0.6734]]],


        [[[ 0.0931, -0.0728, -0.0941, -0.5147,  0.0736],
          [-0.4798, -0.3731, -0.8932,  0.3004, -1.0037],
          [ 0.2598, -0.4027, -0.3718,  0.5731,  0.2922],
          [-0.5001, -0.5964, -0.2343, -1.9222,  0.3342]],

         [[-0.7527, -0.6825, -0.3230, -1.0152, -0.0909],
          [-0.5814, -0.0618,  0.0775, -0.3250, -0.0559],
          [-0.2482, -0.2307,  0.7399, -0.0385,  0.1755],
          [ 0.2701,  0.0309, -0.5631,  0.6244, -0.6386]]]],
       grad_fn=<TransposeBackward0>)

In [28]:
attention_score = (query @ key.transpose(-2 ,-1)) / math.sqrt(d_k)
attention_score

tensor([[[[ 3.7099e-01, -1.2054e-01,  3.6468e-01,  8.3725e-01, -5.4520e-02],
          [-4.9558e-02, -1.2945e-01,  2.4530e-01,  3.5562e-02, -4.2703e-01],
          [-2.2668e-01, -2.9068e-01,  3.0124e-01, -1.0333e-01, -6.7126e-01],
          [-2.2781e-01, -2.2902e-01, -2.0074e-01, -2.0480e-01, -2.0287e-01],
          [-1.4794e-02, -1.6970e-01, -1.6247e-01,  1.5496e-01,  8.4350e-02]],

         [[-3.3616e-02,  1.9560e-02, -3.8386e-02,  5.2151e-01,  3.2878e-01],
          [-1.6372e-01, -1.1551e-02,  1.6483e-02,  1.5859e-01,  1.2499e-01],
          [-2.3306e-01,  3.2176e-03, -1.9670e-02, -5.1747e-02,  1.6120e-01],
          [-6.4701e-02,  1.1616e-02,  5.8313e-02, -2.9886e-01, -1.8842e-02],
          [-2.4203e-01,  6.9530e-05,  5.6568e-02, -3.3081e-01,  3.9251e-02]]],


        [[[ 1.4054e-01, -2.5582e-01, -3.6789e-01, -3.1680e-01, -8.2524e-03],
          [ 1.1425e-01, -5.9002e-02, -4.5706e-02,  6.2097e-02, -9.6488e-02],
          [ 1.7350e-01, -2.7463e-01,  5.0624e-03,  8.6905e-03,  4.2149

### Dropout

In [29]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply dropout with probability p = 0.5
dropout_output = numpy_dropout(x, p=0.5)

print("Input Tensor:\n", x)
print("Dropout Applied:\n", dropout_output)


Input Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Applied:
 [[ 2.  4.  6.]
 [ 8. 10.  0.]]


### Divide by 1-p for maintaining the expectation

test this by multiple runs as follows, we can see the value is nearly the same

In [30]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute expectation of the input
expected_input = np.mean(x)

# Run dropout multiple times and compute mean expectation
num_trials = 10000
expected_dropout_values = [np.mean(numpy_dropout(x, p=0.5)) for _ in range(num_trials)]

# Compute the overall expectation across trials
expected_dropout = np.mean(expected_dropout_values)

print("Expected Value of Input Tensor:", expected_input)
print("Expected Value After Dropout (Averaged over {} runs): {:.4f}".format(num_trials, expected_dropout))


Expected Value of Input Tensor: 3.5
Expected Value After Dropout (Averaged over 10000 runs): 3.5075


In [31]:

def numpy_bernoulli(probabilities):
    """Simulates torch.bernoulli using NumPy."""
    return np.random.binomial(n=3, p=probabilities)

# Example probability tensor (same as in PyTorch example)
probabilities = np.array([0.1, 0.5, 0.9])

# Generate Bernoulli samples
samples = numpy_bernoulli(probabilities)

print("Probabilities:", probabilities)
print("Bernoulli Samples:", samples)


Probabilities: [0.1 0.5 0.9]
Bernoulli Samples: [0 3 3]


## Tokenizers

In [32]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import Whitespace
import pandas as pd

# Sample corpus
corpus = [
    "Hello world!",
    "Hello ChatGPT!",
    "This is a test sentence.",
    "Hello, this is another test.",
    "Test your tokenizer with a sample text.",
    "Banana, banana, BANANA"
]

# Initialize a WordLevel tokenizer
tokenizer = Tokenizer(models.WordLevel(unk_token="[UNK]"))

# Set normalization (lowercasing)
tokenizer.normalizer = Lowercase()

# Set pre-tokenizer (whitespace splitting)
tokenizer.pre_tokenizer = Whitespace()

# Trainer with min_frequency=2
trainer = trainers.WordLevelTrainer(
    min_frequency=2,
    special_tokens=["[UNK]", "[PAD]", "[SOS]", "[EOS]"]
)

# Train tokenizer
tokenizer.train_from_iterator(corpus, trainer)

# Get the vocabulary
vocab = tokenizer.get_vocab()

# Convert to DataFrame for better readability
vocab_df = pd.DataFrame(vocab.items(), columns=["Token", "ID"])

# Print the vocabulary
print(vocab_df)


     Token  ID
0    [UNK]   0
1    [SOS]   2
2     this  12
3     test   8
4    [PAD]   1
5   banana   6
6    hello   7
7        ,   4
8    [EOS]   3
9        .   5
10      is  11
11       a  10
12       !   9


In [33]:
tokenized_corpus = [tokenizer.encode(sentence).tokens for sentence in corpus]
tokenized_corpus

[['hello', '[UNK]', '!'],
 ['hello', '[UNK]', '!'],
 ['this', 'is', 'a', 'test', '[UNK]', '.'],
 ['hello', ',', 'this', 'is', '[UNK]', 'test', '.'],
 ['test', '[UNK]', '[UNK]', '[UNK]', 'a', '[UNK]', '[UNK]', '.'],
 ['banana', ',', 'banana', ',', 'banana']]

In [34]:
# Flatten the list of tokenized words
flat_tokenized_words = [word for sentence in tokenized_corpus for word in sentence]
flat_tokenized_words

['hello',
 '[UNK]',
 '!',
 'hello',
 '[UNK]',
 '!',
 'this',
 'is',
 'a',
 'test',
 '[UNK]',
 '.',
 'hello',
 ',',
 'this',
 'is',
 '[UNK]',
 'test',
 '.',
 'test',
 '[UNK]',
 '[UNK]',
 '[UNK]',
 'a',
 '[UNK]',
 '[UNK]',
 '.',
 'banana',
 ',',
 'banana',
 ',',
 'banana']

In [35]:
# Count the occurrences of each word in the vocabulary
word_counts = Counter(flat_tokenized_words)
word_count_df = pd.DataFrame(word_counts.items(), columns=["Token", "Count"])
word_count_df

Token  Count
0   hello      3
1   [UNK]      9
2       !      2
3    this      2
4      is      2
5       a      2
6    test      3
7       .      3
8       ,      3
9  banana      3

## torch.tensor.size()

In [36]:
# Define tokens
sos_token = torch.tensor([0])  # Start of Sequence <SOS>
eos_token = torch.tensor([1])  # End of Sequence <EOS>
pad_token = 2                  # Padding token

# Example encoded tokens
encoded_input_tokens = torch.tensor([101, 2009, 2003, 1037, 2204, 2154, 102])  # Main sequence
encoded_num_padding_tokens = 3  # Number of padding tokens

# Construct the encoded input using torch.cat()
encoded_input = torch.cat([
    sos_token,  
    encoded_input_tokens,  
    eos_token,  
    torch.tensor([pad_token] * encoded_num_padding_tokens, dtype=torch.int64)
])
encoded_input

tensor([   0,  101, 2009, 2003, 1037, 2204, 2154,  102,    1,    2,    2,    2])

In [37]:
encoded_input.size(0)

12

## encoder_mask

In [38]:
(encoded_input != pad_token).unsqueeze(0).unsqueeze(0).int()

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]], dtype=torch.int32)

## decoder_mask

In [39]:
"""
a is decoded_input, so there is no eos
"""
decoder_input = torch.tensor([0, 12, 13, 2 , 2]) # the real input is 2: 0 is SOS, 2 is pad
# b = torch.tensor([2])
(decoder_input != pad_token).int() # False = 1: means the input rather thant pad token

tensor([1, 1, 1, 0, 0], dtype=torch.int32)

In [40]:
# Build causal_mask with torch.ones
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1)

# Use '&' to make the causal mask align with the length of the input sentence
(decoder_input != pad_token).int() & (causal_mask == 0).type(torch.int) # Convert the 1 to 0, 0 to 1: align with the (a != b).int(), 1 means the real input

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0]]], dtype=torch.int32)

## Dataloader check

In [41]:
class ToyDataset(Dataset):
    def __init__(self, num_samples=5, seq_len=6, pad_token=0):
        self.num_samples = num_samples
        self.seq_len = seq_len
        self.pad_token = pad_token
        
        # Fake tokenized sentences with different lengths
        self.data = [
            [101, 7592, 2088, 102],  # "Hello world"
            [2054, 2024, 2017, 102],  # "How are you?"
            [1045, 2572, 2986, 102],  # "I am fine"
            [2748, 102],  # "Yes"
            [2204, 2872, 102]  # "Good morning"
        ]
        
        # Padding each sequence to `seq_len`
        for i in range(len(self.data)):
            self.data[i] += [self.pad_token] * (self.seq_len - len(self.data[i]))  # Padding
        
    def __len__(self):
        return self.num_samples
    
    def __getitem__(self, idx):
        # Simulated encoder input (source sentence) and decoder input (target sentence)
        encoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        decoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        
        # Create masks
        encoder_mask = (encoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int()  # (1, 1, seq_len)
        decoder_mask = (decoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int() & self.causal_mask(decoded_input.size(0))  # (1, seq_len, seq_len)
        
        return {
            "encoder_input": encoded_input,  # (seq_len)
            "decoder_input": decoded_input,  # (seq_len)
            "encoder_mask": encoder_mask,  # (1, 1, seq_len)
            "decoder_mask": decoder_mask,  # (1, seq_len, seq_len)
            "label": decoded_input,  # (seq_len)
        }
    
    def causal_mask(self, size):
        """ Generate a causal mask for the decoder to prevent attending future tokens """
        mask = torch.tril(torch.ones((size, size), dtype=torch.int))  # Lower triangular matrix
        return mask.unsqueeze(0)  # (1, seq_len, seq_len)


## Transform the tensor before calculating loss

#### Explain the shape transformation in the following:

```
(batch_size, seq_len, tgt_vocab_size) -> (batch_size * seq_len, tgt_vocab_size)  
loss = loss_fn(project_output.view(-1, tokenizer_tgt.get_vocab_size()), label.view(-1))
```

The input shape of the loss function, CrossEntroyLoss, is: (N, C):
- N is the number of samples (each token in this case).
- C is the number of classes (vocabulary size in this case).

Since the output shape of project_layer is: (batch_size, seq_len, tgt_vocab_size).  
example is following:

In [42]:
[   
    # three words(or tokens, actually) in the sentence 1
    [[0.1, 0.2, 0.3, 0.1, 0.3],  # Token 1, Sentence 1
     [0.5, 0.2, 0.1, 0.1, 0.1],  # Token 2, Sentence 1
     [0.2, 0.3, 0.1, 0.3, 0.1]], # Token 3, Sentence 1

    # sentence 2
    [[0.3, 0.1, 0.2, 0.2, 0.2],  # Token 1, Sentence 2
     [0.4, 0.1, 0.1, 0.2, 0.2],  # Token 2, Sentence 2
     [0.1, 0.3, 0.2, 0.2, 0.2]]  # Token 3, Sentence 2
]


[[[0.1, 0.2, 0.3, 0.1, 0.3],
  [0.5, 0.2, 0.1, 0.1, 0.1],
  [0.2, 0.3, 0.1, 0.3, 0.1]],
 [[0.3, 0.1, 0.2, 0.2, 0.2],
  [0.4, 0.1, 0.1, 0.2, 0.2],
  [0.1, 0.3, 0.2, 0.2, 0.2]]]

After reshape to batch_size * seq_len, tgt_vocab_size:

In [43]:
[
    [0.1, 0.2, 0.3, 0.1, 0.3],  # Token 1, Sentence 1
    [0.5, 0.2, 0.1, 0.1, 0.1],  # Token 2, Sentence 1
    [0.2, 0.3, 0.1, 0.3, 0.1],  # Token 3, Sentence 1
    [0.3, 0.1, 0.2, 0.2, 0.2],  # Token 1, Sentence 2
    [0.4, 0.1, 0.1, 0.2, 0.2],  # Token 2, Sentence 2
    [0.1, 0.3, 0.2, 0.2, 0.2]   # Token 3, Sentence 2
]


[[0.1, 0.2, 0.3, 0.1, 0.3],
 [0.5, 0.2, 0.1, 0.1, 0.1],
 [0.2, 0.3, 0.1, 0.3, 0.1],
 [0.3, 0.1, 0.2, 0.2, 0.2],
 [0.4, 0.1, 0.1, 0.2, 0.2],
 [0.1, 0.3, 0.2, 0.2, 0.2]]

the label

In [44]:
label = torch.tensor([
    [2, 0, 1],  # Ground-truth token indices for Sentence 1 (each value represents the correct class index for the corresponding token)
    [4, 3, 1]   # Ground-truth token indices for Sentence 2
])  # Shape: (2, 3)


In [45]:
label.view(-1)

tensor([2, 0, 1, 4, 3, 1])

## torch.tensor v.s. torch.Tensor

In [46]:
torch.tensor(2)

tensor(2)

In [47]:
torch.Tensor(2) # 2 is treated as a shape, not a value, so it creates a tensor of shape (2,) with randomly initialized values.

tensor([-8.1418e+20,  1.9285e-01])

In [ ]:
torch.tensor(2).requires_grad

False

: 