In [22]:
import torch
import torch.nn as nn
import math
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, dataloader

In [23]:
torch.tensor(10)

tensor(10)

In [24]:
d_model = 512
torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [25]:
torch.arange(0, d_model, 2).float()

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [26]:
torch.arange(1, d_model, 2).float()

tensor([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,
         25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,
         49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,
         73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,
         97.,  99., 101., 103., 105., 107., 109., 111., 113., 115., 117., 119.,
        121., 123., 125., 127., 129., 131., 133., 135., 137., 139., 141., 143.,
        145., 147., 149., 151., 153., 155., 157., 159., 161., 163., 165., 167.,
        169., 171., 173., 175., 177., 179., 181., 183., 185., 187., 189., 191.,
        193., 195., 197., 199., 201., 203., 205., 207., 209., 211., 213., 215.,
        217., 219., 221., 223., 225., 227., 229., 231., 233., 235., 237., 239.,
        241., 243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
        265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285., 287.,
        289., 291., 293., 295., 297., 29

In [27]:
d_model = 512

# Using torch.exp
exp_values = torch.exp(torch.arange(0, d_model, 2).float() * (math.log(10000.0) / d_model))

# Using torch.pow
pow_values = torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

# Check if both are the same
print(torch.allclose(exp_values, pow_values))  # Should be True


True


In [28]:
512 // 64

8

In [29]:
512/64

8.0

### Mask in Transfomer

Pad mask

In [30]:
atten_scores = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]]).float()

pad_mask = torch.tensor([[1, 1, 1, 0],
                         [1, 1, 0, 0]])
atten_scores.masked_fill(pad_mask == 0, float('-inf'))

tensor([[1., 2., 3., -inf],
        [5., 6., -inf, -inf]])

the mask change the value in unwanted position to -inf, the value will become 0 after passing softmax

Causal mask

In [31]:
seq_len = 5
# diagonal = 0 : default
# diagonal > 0 (up to length) : shift to upper
# diagonal < 0 (up to length) : shift to lower
# diagonal: the step toward up/down 
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1) # torch.tril is lower triangular matrix
causal_mask

tensor([[[0., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0.]]])

In [32]:
# False: allow attention
# True: Masked(prevent future access)
causal_mask.bool()


tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [33]:
(causal_mask == 0).type(torch.int)

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

### $W_q \times Q$

In [34]:
batch_size = 2
seq_len = 5
d_model = 8  # Model embedding size
h = 2
d_k = d_model // h
q = torch.randn(batch_size, seq_len, d_model)
k = torch.randn(batch_size, seq_len, d_model)
v = torch.randn(batch_size, seq_len, d_model)

w_q = nn.Linear(d_model, d_model)
w_k = nn.Linear(d_model, d_model)
w_v = nn.Linear(d_model, d_model)

In [35]:
w_q

Linear(in_features=8, out_features=8, bias=True)

In [36]:
w_q.weight

Parameter containing:
tensor([[ 0.1428,  0.3431,  0.2994, -0.2965, -0.3392, -0.1656, -0.0291,  0.3435],
        [-0.0415,  0.2341,  0.1061, -0.3383, -0.3043, -0.2228, -0.2744, -0.1954],
        [-0.0100, -0.3456,  0.2087,  0.0631, -0.0827, -0.0090,  0.1976, -0.2517],
        [ 0.2419,  0.0615, -0.3207, -0.0789,  0.3107, -0.1104, -0.1111,  0.0375],
        [ 0.1974, -0.2735, -0.1036, -0.1101, -0.1175,  0.3353, -0.0677,  0.0912],
        [ 0.0311,  0.0332, -0.2990, -0.1517,  0.0467,  0.3297,  0.1928, -0.2025],
        [ 0.1485,  0.3028, -0.3213,  0.3197,  0.0089, -0.1715, -0.0711, -0.2443],
        [-0.0366,  0.1962, -0.1337,  0.0010, -0.0388, -0.1590, -0.0984, -0.0795]],
       requires_grad=True)

In [37]:
w_q.bias

Parameter containing:
tensor([-0.3143, -0.2821,  0.2414,  0.3498, -0.2771,  0.3446, -0.3180,  0.3464],
       requires_grad=True)

In [38]:
q

tensor([[[ 0.0353, -0.7473,  0.5334, -1.1285, -0.1148,  0.5366, -1.0217,
           0.3782],
         [ 0.3393,  0.2364,  0.5980, -0.0357,  1.4332, -0.6502,  1.2400,
          -0.3136],
         [ 0.5190, -0.4202,  1.8979, -0.1536,  0.8054, -0.5070,  0.2912,
          -0.6475],
         [ 2.0307, -0.6709, -1.5005,  0.4828,  0.6329,  0.5436,  0.8358,
          -0.6920],
         [-1.1621,  2.2484,  1.8086, -0.4363, -0.2893,  1.6981, -0.1453,
          -0.8524]],

        [[ 0.0945,  1.1840, -1.0047, -0.0799,  0.2158, -2.0745, -0.4414,
          -0.2626],
         [-0.3234,  0.2133, -0.4673, -0.9813, -0.4884, -1.5280, -0.3162,
          -1.3755],
         [-0.1343, -1.5692,  0.5080,  0.6149, -1.0885, -0.8093, -0.5187,
          -1.1083],
         [ 0.1174, -0.3709,  0.6636,  0.3416,  1.1465, -1.8643, -0.0097,
           0.8427],
         [ 0.8460, -1.8956,  1.5724, -0.7767,  0.6167,  0.0636, -1.0848,
          -1.5269]]])

In [39]:
w_q(q)

tensor([[[ 0.0384,  0.1017,  0.2470,  0.2632,  0.3002,  0.2306, -1.1840,
           0.1156],
         [-0.5174, -0.7355,  0.4901,  0.6250, -0.8318,  0.3447, -0.2869,
           0.2512],
         [-0.1906, -0.2343,  0.9263,  0.1026, -0.5829, -0.1397, -0.7956,
           0.0633],
         [-1.4137, -1.2537,  0.4525,  1.2607,  0.3977,  1.2709,  0.4389,
           0.2033],
         [ 0.4905,  0.5481,  0.0202, -0.6318, -0.7254,  0.5996, -0.6056,
           0.4111]],

        [[ 0.0212,  0.4806, -0.4036,  1.1092, -1.1845, -0.0064,  0.8050,
           1.0954],
         [-0.1808,  0.9083,  0.3494,  0.5124, -0.8019,  0.3211,  0.1512,
           0.8639],
         [-0.7642,  0.0723,  1.2037, -0.2235, -0.2041, -0.1502, -0.3431,
           0.2860],
         [-0.1178, -0.5145,  0.2365,  0.7103, -0.9412, -0.6479, -0.3922,
           0.3669],
         [-0.8553,  0.0628,  1.2856,  0.2428,  0.2140,  0.1054, -1.0753,
          -0.0735]]], grad_fn=<ViewBackward0>)

In [40]:
# w_q(q) equals to q * w_q.wieght + bias
assert torch.allclose(w_q(q), torch.matmul(q, w_q.weight.T) + w_q.bias), "w_q(q) doesn't equl to q*w_q^T + bias"

In [41]:
# assert torch.allclose(w_q(q), q @ w_q.weight.T), 'they are different'

In [42]:
# If w = nn.Linear(d_model, d_model, bias=False) then they will be the same
w_test = nn.Linear(d_model, d_model, bias=False)
assert torch.allclose(w_test(q), q @ w_test.weight.T), 'they are different'

In [43]:
query = w_q(q)
key = w_k(k)
value = w_v(v)
query.shape

torch.Size([2, 5, 8])

In [44]:
# keep the batch size and seq_len, decompose the matrix into smaller matrix
# so we can give each small matrix different head
# later, we can perform independent attention calculations for each head
query.view(query.shape[0], query.shape[1], h, d_k).shape

torch.Size([2, 5, 2, 4])

In [45]:
"""
The reason for using (batch_size, h, seq_len, d_k) instead of (batch_size, seq_len, h, d_k) is that:

The attention mechanism operates independently across heads.
Each head will perform self-attention on its own set of d_k-dimensional vectors.
The typical implementation of multi-head attention expects the shape (batch_size, h, seq_len, d_k).
When performing matrix multiplications (like query @ key.T), we want to apply attention per head.
This format is easier for batched computations in PyTorch and TensorFlow.
"""

query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2).shape

torch.Size([2, 2, 5, 4])

In [46]:
query = query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2)
key = key.view(key.shape[0], key.shape[1], h, d_k).transpose(1, 2)
value = value.view(value.shape[0], value.shape[1], h, d_k).transpose(1, 2)


In [47]:
query.transpose(-2, -1)

tensor([[[[ 0.0384, -0.5174, -0.1906, -1.4137,  0.4905],
          [ 0.1017, -0.7355, -0.2343, -1.2537,  0.5481],
          [ 0.2470,  0.4901,  0.9263,  0.4525,  0.0202],
          [ 0.2632,  0.6250,  0.1026,  1.2607, -0.6318]],

         [[ 0.3002, -0.8318, -0.5829,  0.3977, -0.7254],
          [ 0.2306,  0.3447, -0.1397,  1.2709,  0.5996],
          [-1.1840, -0.2869, -0.7956,  0.4389, -0.6056],
          [ 0.1156,  0.2512,  0.0633,  0.2033,  0.4111]]],


        [[[ 0.0212, -0.1808, -0.7642, -0.1178, -0.8553],
          [ 0.4806,  0.9083,  0.0723, -0.5145,  0.0628],
          [-0.4036,  0.3494,  1.2037,  0.2365,  1.2856],
          [ 1.1092,  0.5124, -0.2235,  0.7103,  0.2428]],

         [[-1.1845, -0.8019, -0.2041, -0.9412,  0.2140],
          [-0.0064,  0.3211, -0.1502, -0.6479,  0.1054],
          [ 0.8050,  0.1512, -0.3431, -0.3922, -1.0753],
          [ 1.0954,  0.8639,  0.2860,  0.3669, -0.0735]]]],
       grad_fn=<TransposeBackward0>)

In [48]:
attention_score = (query @ key.transpose(-2 ,-1)) / math.sqrt(d_k)
attention_score

tensor([[[[-0.0943,  0.0114,  0.0344, -0.1186,  0.0603],
          [-0.5520, -0.1646, -0.1299, -0.2376, -0.0683],
          [-0.4892, -0.2988, -0.2007, -0.1164, -0.1496],
          [-1.0023, -0.1987, -0.3948, -0.7448,  0.0721],
          [ 0.3091, -0.0122,  0.0511,  0.2615, -0.0621]],

         [[-0.1094,  0.2777,  0.0222, -0.8329, -0.0671],
          [-0.1156,  0.2997, -0.2060, -0.7361,  0.4796],
          [-0.2014,  0.4486, -0.0907, -1.0593,  0.4324],
          [ 0.2370, -0.3385, -0.0294,  0.8026, -0.3635],
          [-0.1252,  0.3277, -0.2443, -0.9578,  0.4235]]],


        [[[ 0.7129,  0.1607,  0.4501,  0.2432, -0.0638],
          [ 1.0623,  0.0538,  0.4733,  0.4917, -0.3434],
          [-0.0287, -0.6762, -0.1958,  0.7193, -0.5443],
          [-0.3231, -0.5690, -0.1879,  0.2875, -0.3528],
          [ 0.0710, -0.8597, -0.1486,  0.9305, -0.7185]],

         [[ 0.0904,  0.4654, -0.1059,  0.4597,  0.4722],
          [-0.2340,  0.4198, -0.1431,  0.3983,  0.8403],
          [-0.3912,  0.

### Dropout

In [49]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply dropout with probability p = 0.5
dropout_output = numpy_dropout(x, p=0.5)

print("Input Tensor:\n", x)
print("Dropout Applied:\n", dropout_output)


Input Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Applied:
 [[0. 0. 0.]
 [0. 0. 0.]]


### Divide by 1-p for maintaining the expectation

test this by multiple runs as follows, we can see the value is nearly the same

In [50]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute expectation of the input
expected_input = np.mean(x)

# Run dropout multiple times and compute mean expectation
num_trials = 10000
expected_dropout_values = [np.mean(numpy_dropout(x, p=0.5)) for _ in range(num_trials)]

# Compute the overall expectation across trials
expected_dropout = np.mean(expected_dropout_values)

print("Expected Value of Input Tensor:", expected_input)
print("Expected Value After Dropout (Averaged over {} runs): {:.4f}".format(num_trials, expected_dropout))


Expected Value of Input Tensor: 3.5
Expected Value After Dropout (Averaged over 10000 runs): 3.4600


In [51]:

def numpy_bernoulli(probabilities):
    """Simulates torch.bernoulli using NumPy."""
    return np.random.binomial(n=3, p=probabilities)

# Example probability tensor (same as in PyTorch example)
probabilities = np.array([0.1, 0.5, 0.9])

# Generate Bernoulli samples
samples = numpy_bernoulli(probabilities)

print("Probabilities:", probabilities)
print("Bernoulli Samples:", samples)


Probabilities: [0.1 0.5 0.9]
Bernoulli Samples: [0 1 3]


## Tokenizers

In [52]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import Whitespace
import pandas as pd

# Sample corpus
corpus = [
    "Hello world!",
    "Hello ChatGPT!",
    "This is a test sentence.",
    "Hello, this is another test.",
    "Test your tokenizer with a sample text.",
    "Banana, banana, BANANA"
]

# Initialize a WordLevel tokenizer
tokenizer = Tokenizer(models.WordLevel(unk_token="[UNK]"))

# Set normalization (lowercasing)
tokenizer.normalizer = Lowercase()

# Set pre-tokenizer (whitespace splitting)
tokenizer.pre_tokenizer = Whitespace()

# Trainer with min_frequency=2
trainer = trainers.WordLevelTrainer(
    min_frequency=2,
    special_tokens=["[UNK]", "[PAD]", "[SOS]", "[EOS]"]
)

# Train tokenizer
tokenizer.train_from_iterator(corpus, trainer)

# Get the vocabulary
vocab = tokenizer.get_vocab()

# Convert to DataFrame for better readability
vocab_df = pd.DataFrame(vocab.items(), columns=["Token", "ID"])

# Print the vocabulary
print(vocab_df)


     Token  ID
0    hello   7
1    [SOS]   2
2        ,   4
3     this  12
4        a  10
5     test   8
6        .   5
7    [EOS]   3
8    [UNK]   0
9        !   9
10      is  11
11  banana   6
12   [PAD]   1


In [53]:
tokenized_corpus = [tokenizer.encode(sentence).tokens for sentence in corpus]
tokenized_corpus

[['hello', '[UNK]', '!'],
 ['hello', '[UNK]', '!'],
 ['this', 'is', 'a', 'test', '[UNK]', '.'],
 ['hello', ',', 'this', 'is', '[UNK]', 'test', '.'],
 ['test', '[UNK]', '[UNK]', '[UNK]', 'a', '[UNK]', '[UNK]', '.'],
 ['banana', ',', 'banana', ',', 'banana']]

In [54]:
# Flatten the list of tokenized words
flat_tokenized_words = [word for sentence in tokenized_corpus for word in sentence]
flat_tokenized_words

['hello',
 '[UNK]',
 '!',
 'hello',
 '[UNK]',
 '!',
 'this',
 'is',
 'a',
 'test',
 '[UNK]',
 '.',
 'hello',
 ',',
 'this',
 'is',
 '[UNK]',
 'test',
 '.',
 'test',
 '[UNK]',
 '[UNK]',
 '[UNK]',
 'a',
 '[UNK]',
 '[UNK]',
 '.',
 'banana',
 ',',
 'banana',
 ',',
 'banana']

In [55]:
# Count the occurrences of each word in the vocabulary
word_counts = Counter(flat_tokenized_words)
word_count_df = pd.DataFrame(word_counts.items(), columns=["Token", "Count"])
word_count_df

Token  Count
0   hello      3
1   [UNK]      9
2       !      2
3    this      2
4      is      2
5       a      2
6    test      3
7       .      3
8       ,      3
9  banana      3

## torch.tensor.size()

In [56]:
# Define tokens
sos_token = torch.tensor([0])  # Start of Sequence <SOS>
eos_token = torch.tensor([1])  # End of Sequence <EOS>
pad_token = 2                  # Padding token

# Example encoded tokens
encoded_input_tokens = torch.tensor([101, 2009, 2003, 1037, 2204, 2154, 102])  # Main sequence
encoded_num_padding_tokens = 3  # Number of padding tokens

# Construct the encoded input using torch.cat()
encoded_input = torch.cat([
    sos_token,  
    encoded_input_tokens,  
    eos_token,  
    torch.tensor([pad_token] * encoded_num_padding_tokens, dtype=torch.int64)
])
encoded_input

tensor([   0,  101, 2009, 2003, 1037, 2204, 2154,  102,    1,    2,    2,    2])

In [57]:
encoded_input.size(0)

12

## encoder_mask

In [58]:
(encoded_input != pad_token).unsqueeze(0).unsqueeze(0).int()

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]], dtype=torch.int32)

## decoder_mask

In [59]:
"""
a is decoded_input, so there is no eos
"""
decoder_input = torch.tensor([0, 12, 13, 2 , 2]) # the real input is 2: 0 is SOS, 2 is pad
# b = torch.tensor([2])
(decoder_input != pad_token).int() # False = 1: means the input rather thant pad token

tensor([1, 1, 1, 0, 0], dtype=torch.int32)

In [60]:
# Build causal_mask with torch.ones
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1)

# Use '&' to make the causal mask align with the length of the input sentence
(decoder_input != pad_token).int() & (causal_mask == 0).type(torch.int) # Convert the 1 to 0, 0 to 1: align with the (a != b).int(), 1 means the real input

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0]]], dtype=torch.int32)

## Dataloader check

In [61]:
class ToyDataset(Dataset):
    def __init__(self, num_samples=5, seq_len=6, pad_token=0):
        self.num_samples = num_samples
        self.seq_len = seq_len
        self.pad_token = pad_token
        
        # Fake tokenized sentences with different lengths
        self.data = [
            [101, 7592, 2088, 102],  # "Hello world"
            [2054, 2024, 2017, 102],  # "How are you?"
            [1045, 2572, 2986, 102],  # "I am fine"
            [2748, 102],  # "Yes"
            [2204, 2872, 102]  # "Good morning"
        ]
        
        # Padding each sequence to `seq_len`
        for i in range(len(self.data)):
            self.data[i] += [self.pad_token] * (self.seq_len - len(self.data[i]))  # Padding
        
    def __len__(self):
        return self.num_samples
    
    def __getitem__(self, idx):
        # Simulated encoder input (source sentence) and decoder input (target sentence)
        encoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        decoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        
        # Create masks
        encoder_mask = (encoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int()  # (1, 1, seq_len)
        decoder_mask = (decoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int() & self.causal_mask(decoded_input.size(0))  # (1, seq_len, seq_len)
        
        return {
            "encoder_input": encoded_input,  # (seq_len)
            "decoder_input": decoded_input,  # (seq_len)
            "encoder_mask": encoder_mask,  # (1, 1, seq_len)
            "decoder_mask": decoder_mask,  # (1, seq_len, seq_len)
            "label": decoded_input,  # (seq_len)
        }
    
    def causal_mask(self, size):
        """ Generate a causal mask for the decoder to prevent attending future tokens """
        mask = torch.tril(torch.ones((size, size), dtype=torch.int))  # Lower triangular matrix
        return mask.unsqueeze(0)  # (1, seq_len, seq_len)


## Transform the tensor before calculating loss

#### Explain the shape transformation in the following:

```
(batch_size, seq_len, tgt_vocab_size) -> (batch_size * seq_len, tgt_vocab_size)  
loss = loss_fn(project_output.view(-1, tokenizer_tgt.get_vocab_size()), label.view(-1))
```

The input shape of the loss function, CrossEntroyLoss, is: (N, C):
- N is the number of samples (each token in this case).
- C is the number of classes (vocabulary size in this case).

Since the output shape of project_layer is: (batch_size, seq_len, tgt_vocab_size).  
example is following:

In [62]:
[   
    # three words(or tokens, actually) in the sentence 1
    [[0.1, 0.2, 0.3, 0.1, 0.3],  # Token 1, Sentence 1
     [0.5, 0.2, 0.1, 0.1, 0.1],  # Token 2, Sentence 1
     [0.2, 0.3, 0.1, 0.3, 0.1]], # Token 3, Sentence 1

    # sentence 2
    [[0.3, 0.1, 0.2, 0.2, 0.2],  # Token 1, Sentence 2
     [0.4, 0.1, 0.1, 0.2, 0.2],  # Token 2, Sentence 2
     [0.1, 0.3, 0.2, 0.2, 0.2]]  # Token 3, Sentence 2
]


[[[0.1, 0.2, 0.3, 0.1, 0.3],
  [0.5, 0.2, 0.1, 0.1, 0.1],
  [0.2, 0.3, 0.1, 0.3, 0.1]],
 [[0.3, 0.1, 0.2, 0.2, 0.2],
  [0.4, 0.1, 0.1, 0.2, 0.2],
  [0.1, 0.3, 0.2, 0.2, 0.2]]]

After reshape to batch_size * seq_len, tgt_vocab_size:

In [63]:
[
    [0.1, 0.2, 0.3, 0.1, 0.3],  # Token 1, Sentence 1
    [0.5, 0.2, 0.1, 0.1, 0.1],  # Token 2, Sentence 1
    [0.2, 0.3, 0.1, 0.3, 0.1],  # Token 3, Sentence 1
    [0.3, 0.1, 0.2, 0.2, 0.2],  # Token 1, Sentence 2
    [0.4, 0.1, 0.1, 0.2, 0.2],  # Token 2, Sentence 2
    [0.1, 0.3, 0.2, 0.2, 0.2]   # Token 3, Sentence 2
]


[[0.1, 0.2, 0.3, 0.1, 0.3],
 [0.5, 0.2, 0.1, 0.1, 0.1],
 [0.2, 0.3, 0.1, 0.3, 0.1],
 [0.3, 0.1, 0.2, 0.2, 0.2],
 [0.4, 0.1, 0.1, 0.2, 0.2],
 [0.1, 0.3, 0.2, 0.2, 0.2]]

the label

In [64]:
label = torch.tensor([
    [2, 0, 1],  # Ground-truth token indices for Sentence 1 (each value represents the correct class index for the corresponding token)
    [4, 3, 1]   # Ground-truth token indices for Sentence 2
])  # Shape: (2, 3)


In [65]:
label.view(-1)

tensor([2, 0, 1, 4, 3, 1])

## torch.tensor v.s. torch.Tensor

In [70]:
torch.tensor(2)

tensor(2)

In [71]:
torch.Tensor(2) # 2 is treated as a shape, not a value, so it creates a tensor of shape (2,) with randomly initialized values.

tensor([9.2196e-41, 1.8980e+01])

In [ ]:
torch.tensor(2).requires_grad