In [3]:
import torch
import torch.nn as nn
import math
import numpy as np
from collections import Counter

In [4]:
torch.tensor(10)

tensor(10)

In [5]:
d_model = 512
torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [6]:
torch.arange(0, d_model, 2).float()

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [7]:
torch.arange(1, d_model, 2).float()

tensor([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,
         25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,
         49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,
         73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,
         97.,  99., 101., 103., 105., 107., 109., 111., 113., 115., 117., 119.,
        121., 123., 125., 127., 129., 131., 133., 135., 137., 139., 141., 143.,
        145., 147., 149., 151., 153., 155., 157., 159., 161., 163., 165., 167.,
        169., 171., 173., 175., 177., 179., 181., 183., 185., 187., 189., 191.,
        193., 195., 197., 199., 201., 203., 205., 207., 209., 211., 213., 215.,
        217., 219., 221., 223., 225., 227., 229., 231., 233., 235., 237., 239.,
        241., 243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
        265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285., 287.,
        289., 291., 293., 295., 297., 29

In [8]:
d_model = 512

# Using torch.exp
exp_values = torch.exp(torch.arange(0, d_model, 2).float() * (math.log(10000.0) / d_model))

# Using torch.pow
pow_values = torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

# Check if both are the same
print(torch.allclose(exp_values, pow_values))  # Should be True


True


In [9]:
512 // 64

8

In [10]:
512/64

8.0

### Mask in Transfomer

Pad mask

In [11]:
atten_scores = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]]).float()

pad_mask = torch.tensor([[1, 1, 1, 0],
                         [1, 1, 0, 0]])
atten_scores.masked_fill(pad_mask == 0, float('-inf'))

tensor([[1., 2., 3., -inf],
        [5., 6., -inf, -inf]])

the mask change the value in unwanted position to -inf, the value will become 0 after passing softmax

Causal mask

In [ ]:
seq_len = 5
# diagonal = 0 : default
# diagonal > 0 (up to length) : shift to upper
# diagonal < 0 (up to length) : shift to lower
# diagonal: the step toward up/down 
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1) # torch.tril is lower triangular matrix
causal_mask

tensor([[[0., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0.]]])

In [13]:
# False: allow attention
# True: Masked(prevent future access)
causal_mask.bool()


tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [49]:
(causal_mask == 0).type(torch.int)

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

### $W_q \times Q$

In [14]:
batch_size = 2
seq_len = 4
d_model = 8  # Model embedding size
h = 2
d_k = d_model // h
q = torch.randn(batch_size, seq_len, d_model)
k = torch.randn(batch_size, seq_len, d_model)
v = torch.randn(batch_size, seq_len, d_model)

w_q = nn.Linear(d_model, d_model)
w_k = nn.Linear(d_model, d_model)
w_v = nn.Linear(d_model, d_model)

In [15]:
w_q

Linear(in_features=8, out_features=8, bias=True)

In [16]:
w_q.weight

Parameter containing:
tensor([[ 0.2956,  0.3017,  0.2095,  0.0102,  0.3108, -0.1231,  0.2842, -0.0630],
        [-0.3499,  0.1831,  0.1254,  0.2108, -0.1379, -0.0171, -0.2342, -0.1333],
        [-0.0991, -0.3430, -0.3122, -0.2325, -0.3493,  0.3280,  0.0291,  0.1152],
        [-0.3421,  0.3067, -0.0454,  0.3392,  0.2325, -0.0272, -0.2155,  0.0931],
        [ 0.1655, -0.2998, -0.0820,  0.1559,  0.0969, -0.2340,  0.3254,  0.2499],
        [-0.0936, -0.2997, -0.2214,  0.2834,  0.0294,  0.1918,  0.0258,  0.2275],
        [-0.3502,  0.0166, -0.2673,  0.1811, -0.2089, -0.1333, -0.2844,  0.2587],
        [-0.1116,  0.2407,  0.0392,  0.2633,  0.3190, -0.0115,  0.0292,  0.2390]],
       requires_grad=True)

In [17]:
w_q.bias

Parameter containing:
tensor([ 0.2430,  0.1544, -0.3214, -0.0270, -0.2740, -0.2984,  0.0115, -0.0125],
       requires_grad=True)

In [18]:
q

tensor([[[-1.2811,  2.7480, -0.7686,  0.5561,  0.4005, -0.2282,  1.3327,
          -0.9030],
         [-0.3814, -1.5869, -0.8211,  0.8302,  1.1556, -0.2978,  0.8301,
          -1.0593],
         [ 0.5936, -0.8763,  0.6146,  1.3449, -0.3268, -0.1439, -0.3934,
           0.1920],
         [-0.5722,  0.3083,  0.1601,  2.3065,  0.9289, -1.3594, -0.3375,
           0.5340]],

        [[ 1.0031, -0.4555, -1.0818, -1.1258, -0.2213,  0.5848,  0.3411,
           1.5733],
         [-0.3406,  1.5853, -0.3481, -0.7200,  0.6413,  1.0314, -0.0131,
           1.4986],
         [ 1.0077, -0.9961,  0.7193, -1.0495,  0.0678,  0.0714, -0.4262,
          -1.1070],
         [-0.2852, -0.2859, -0.1054,  0.0674, -0.4261,  1.0317, -0.5686,
          -0.6572]]])

In [19]:
w_q(q)

tensor([[[ 1.1264,  0.8836, -1.3063,  1.2058, -0.8600, -0.8772,  0.1460,
           0.8616],
         [ 0.1865, -0.1380, -0.2751, -0.0651,  0.5225,  0.3872, -0.2233,
          -0.0223],
         [ 0.0888,  0.2609, -0.5064, -0.0400,  0.1683,  0.1501,  0.1174,
           0.0203],
         [ 0.5505,  0.8204, -1.6753,  1.4138,  0.3170,  0.1604,  0.8132,
           1.1689]],

        [[ 0.0212, -0.9221,  0.7952, -0.8371,  0.2876,  0.1370,  0.0163,
          -0.2642],
         [ 0.5147,  0.0657, -0.2689,  0.6108, -0.6984, -0.3113,  0.2398,
           0.7544],
         [ 0.3411, -0.2746, -0.2003, -1.0633, -0.4565, -0.7979, -0.9291,
          -0.8691],
         [-0.3286,  0.4648,  0.2172, -0.0553, -0.8483, -0.1224,  0.0901,
          -0.3574]]], grad_fn=<ViewBackward0>)

In [20]:
# w_q(q) equals to q * w_q.wieght + bias
assert torch.allclose(w_q(q), torch.matmul(q, w_q.weight.T) + w_q.bias), "w_q(q) doesn't equl to q*w_q^T + bias"

In [21]:
# assert torch.allclose(w_q(q), q @ w_q.weight.T), 'they are different'

In [22]:
# If w = nn.Linear(d_model, d_model, bias=False) then they will be the same
w_test = nn.Linear(d_model, d_model, bias=False)
assert torch.allclose(w_test(q), q @ w_test.weight.T), 'they are different'

In [23]:
query = w_q(q)
key = w_k(k)
value = w_v(v)
query.shape

torch.Size([2, 4, 8])

In [24]:
# keep the batch size and seq_len, decompose the matrix into smaller matrix
# so we can give each small matrix different head
# later, we can perform independent attention calculations for each head
query.view(query.shape[0], query.shape[1], h, d_k).shape

torch.Size([2, 4, 2, 4])

In [25]:
"""
The reason for using (batch_size, h, seq_len, d_k) instead of (batch_size, seq_len, h, d_k) is that:

The attention mechanism operates independently across heads.
Each head will perform self-attention on its own set of d_k-dimensional vectors.
The typical implementation of multi-head attention expects the shape (batch_size, h, seq_len, d_k).
When performing matrix multiplications (like query @ key.T), we want to apply attention per head.
This format is easier for batched computations in PyTorch and TensorFlow.
"""

query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2).shape

torch.Size([2, 2, 4, 4])

In [26]:
query = query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2)
key = key.view(key.shape[0], key.shape[1], h, d_k).transpose(1, 2)
value = value.view(value.shape[0], value.shape[1], h, d_k).transpose(1, 2)


In [27]:
query.transpose(-2, -1)

tensor([[[[ 1.1264,  0.1865,  0.0888,  0.5505],
          [ 0.8836, -0.1380,  0.2609,  0.8204],
          [-1.3063, -0.2751, -0.5064, -1.6753],
          [ 1.2058, -0.0651, -0.0400,  1.4138]],

         [[-0.8600,  0.5225,  0.1683,  0.3170],
          [-0.8772,  0.3872,  0.1501,  0.1604],
          [ 0.1460, -0.2233,  0.1174,  0.8132],
          [ 0.8616, -0.0223,  0.0203,  1.1689]]],


        [[[ 0.0212,  0.5147,  0.3411, -0.3286],
          [-0.9221,  0.0657, -0.2746,  0.4648],
          [ 0.7952, -0.2689, -0.2003,  0.2172],
          [-0.8371,  0.6108, -1.0633, -0.0553]],

         [[ 0.2876, -0.6984, -0.4565, -0.8483],
          [ 0.1370, -0.3113, -0.7979, -0.1224],
          [ 0.0163,  0.2398, -0.9291,  0.0901],
          [-0.2642,  0.7544, -0.8691, -0.3574]]]],
       grad_fn=<TransposeBackward0>)

In [28]:
attention_score = (query @ key.transpose(-2 ,-1)) / math.sqrt(d_k)
attention_score

tensor([[[[-0.9157,  0.0513,  0.1330, -0.6412],
          [-0.0147,  0.1114,  0.0712, -0.0262],
          [-0.1894,  0.0404, -0.0327, -0.0787],
          [-0.9802, -0.0308, -0.0956, -0.5266]],

         [[ 0.3311,  0.1983,  0.4796, -0.2200],
          [-0.1497, -0.0800, -0.1673,  0.0292],
          [-0.0480,  0.0113, -0.0137,  0.0716],
          [ 0.0246,  0.2638,  0.3976,  0.2193]]],


        [[[ 0.5027,  0.4139,  0.5343,  0.5886],
          [-0.2383, -0.1402, -0.2087,  0.1509],
          [ 0.5358,  0.4792,  0.1615,  0.2448],
          [ 0.1215,  0.0500,  0.0221, -0.2017]],

         [[ 0.0333, -0.1112, -0.0366, -0.0993],
          [ 0.0420,  0.2686,  0.0544,  0.3847],
          [-0.0233,  0.0463,  0.3182, -0.1123],
          [ 0.1555,  0.2327, -0.1697,  0.0707]]]], grad_fn=<DivBackward0>)

### Dropout

In [29]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply dropout with probability p = 0.5
dropout_output = numpy_dropout(x, p=0.5)

print("Input Tensor:\n", x)
print("Dropout Applied:\n", dropout_output)


Input Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Applied:
 [[0. 0. 0.]
 [0. 0. 0.]]


### Divide by 1-p for maintaining the expectation

test this by multiple runs as follows, we can see the value is nearly the same

In [30]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute expectation of the input
expected_input = np.mean(x)

# Run dropout multiple times and compute mean expectation
num_trials = 10000
expected_dropout_values = [np.mean(numpy_dropout(x, p=0.5)) for _ in range(num_trials)]

# Compute the overall expectation across trials
expected_dropout = np.mean(expected_dropout_values)

print("Expected Value of Input Tensor:", expected_input)
print("Expected Value After Dropout (Averaged over {} runs): {:.4f}".format(num_trials, expected_dropout))


Expected Value of Input Tensor: 3.5
Expected Value After Dropout (Averaged over 10000 runs): 3.5030


In [31]:

def numpy_bernoulli(probabilities):
    """Simulates torch.bernoulli using NumPy."""
    return np.random.binomial(n=3, p=probabilities)

# Example probability tensor (same as in PyTorch example)
probabilities = np.array([0.1, 0.5, 0.9])

# Generate Bernoulli samples
samples = numpy_bernoulli(probabilities)

print("Probabilities:", probabilities)
print("Bernoulli Samples:", samples)


Probabilities: [0.1 0.5 0.9]
Bernoulli Samples: [0 3 3]


## Tokenizers

In [32]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import Whitespace
import pandas as pd

# Sample corpus
corpus = [
    "Hello world!",
    "Hello ChatGPT!",
    "This is a test sentence.",
    "Hello, this is another test.",
    "Test your tokenizer with a sample text.",
    "Banana, banana, BANANA"
]

# Initialize a WordLevel tokenizer
tokenizer = Tokenizer(models.WordLevel(unk_token="[UNK]"))

# Set normalization (lowercasing)
tokenizer.normalizer = Lowercase()

# Set pre-tokenizer (whitespace splitting)
tokenizer.pre_tokenizer = Whitespace()

# Trainer with min_frequency=2
trainer = trainers.WordLevelTrainer(
    min_frequency=2,
    special_tokens=["[UNK]", "[PAD]", "[SOS]", "[EOS]"]
)

# Train tokenizer
tokenizer.train_from_iterator(corpus, trainer)

# Get the vocabulary
vocab = tokenizer.get_vocab()

# Convert to DataFrame for better readability
vocab_df = pd.DataFrame(vocab.items(), columns=["Token", "ID"])

# Print the vocabulary
print(vocab_df)


     Token  ID
0    [SOS]   2
1        ,   4
2        .   5
3        !   9
4    hello   7
5     this  12
6   banana   6
7    [EOS]   3
8    [PAD]   1
9    [UNK]   0
10    test   8
11      is  11
12       a  10


In [33]:
tokenized_corpus = [tokenizer.encode(sentence).tokens for sentence in corpus]
tokenized_corpus

[['hello', '[UNK]', '!'],
 ['hello', '[UNK]', '!'],
 ['this', 'is', 'a', 'test', '[UNK]', '.'],
 ['hello', ',', 'this', 'is', '[UNK]', 'test', '.'],
 ['test', '[UNK]', '[UNK]', '[UNK]', 'a', '[UNK]', '[UNK]', '.'],
 ['banana', ',', 'banana', ',', 'banana']]

In [34]:
# Flatten the list of tokenized words
flat_tokenized_words = [word for sentence in tokenized_corpus for word in sentence]
flat_tokenized_words

['hello',
 '[UNK]',
 '!',
 'hello',
 '[UNK]',
 '!',
 'this',
 'is',
 'a',
 'test',
 '[UNK]',
 '.',
 'hello',
 ',',
 'this',
 'is',
 '[UNK]',
 'test',
 '.',
 'test',
 '[UNK]',
 '[UNK]',
 '[UNK]',
 'a',
 '[UNK]',
 '[UNK]',
 '.',
 'banana',
 ',',
 'banana',
 ',',
 'banana']

In [35]:
# Count the occurrences of each word in the vocabulary
word_counts = Counter(flat_tokenized_words)
word_count_df = pd.DataFrame(word_counts.items(), columns=["Token", "Count"])
word_count_df

Token  Count
0   hello      3
1   [UNK]      9
2       !      2
3    this      2
4      is      2
5       a      2
6    test      3
7       .      3
8       ,      3
9  banana      3

### torch.tensor.size()

In [40]:
# Define tokens
sos_token = torch.tensor([0])  # Start of Sequence <SOS>
eos_token = torch.tensor([1])  # End of Sequence <EOS>
pad_token = 2                  # Padding token

# Example encoded tokens
encoded_input_tokens = torch.tensor([101, 2009, 2003, 1037, 2204, 2154, 102])  # Main sequence
encoded_num_padding_tokens = 3  # Number of padding tokens

# Construct the encoded input using torch.cat()
encoded_input = torch.cat([
    sos_token,  
    encoded_input_tokens,  
    eos_token,  
    torch.tensor([pad_token] * encoded_num_padding_tokens, dtype=torch.int64)
])
encoded_input

tensor([   0,  101, 2009, 2003, 1037, 2204, 2154,  102,    1,    2,    2,    2])

In [51]:
encoded_input.size(0)

12

encoder_mask

In [ ]:
"""
a is decoded_input, so there is no eos
"""
a = torch.tensor([0, 12, 13, 2 , 2]) # the real input is 2: 0 is SOS, 2 is pad
b = 2
(a != b).int() # False = 1: means the input rather thant pad token

tensor([1, 1, 1, 0, 0], dtype=torch.int32)

In [63]:
# Build causal_mask with torch.ones
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1)

# Use '&' to make the causal mask align with the length of the input sentence
(a != b).int() & (causal_mask == 0).type(torch.int) # Convert the 1 to 0, 0 to 1: align with the (a != b).int(), 1 means the real input

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0]]], dtype=torch.int32)