In [41]:
import torch
import torch.nn as nn
import math
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, dataloader

In [2]:
torch.tensor(10)

tensor(10)

In [3]:
d_model = 512
torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [4]:
torch.arange(0, d_model, 2).float()

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [5]:
torch.arange(1, d_model, 2).float()

tensor([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,
         25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,
         49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,
         73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,
         97.,  99., 101., 103., 105., 107., 109., 111., 113., 115., 117., 119.,
        121., 123., 125., 127., 129., 131., 133., 135., 137., 139., 141., 143.,
        145., 147., 149., 151., 153., 155., 157., 159., 161., 163., 165., 167.,
        169., 171., 173., 175., 177., 179., 181., 183., 185., 187., 189., 191.,
        193., 195., 197., 199., 201., 203., 205., 207., 209., 211., 213., 215.,
        217., 219., 221., 223., 225., 227., 229., 231., 233., 235., 237., 239.,
        241., 243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
        265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285., 287.,
        289., 291., 293., 295., 297., 29

In [6]:
d_model = 512

# Using torch.exp
exp_values = torch.exp(torch.arange(0, d_model, 2).float() * (math.log(10000.0) / d_model))

# Using torch.pow
pow_values = torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

# Check if both are the same
print(torch.allclose(exp_values, pow_values))  # Should be True


True


In [7]:
512 // 64

8

In [8]:
512/64

8.0

### Mask in Transfomer

Pad mask

In [9]:
atten_scores = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]]).float()

pad_mask = torch.tensor([[1, 1, 1, 0],
                         [1, 1, 0, 0]])
atten_scores.masked_fill(pad_mask == 0, float('-inf'))

tensor([[1., 2., 3., -inf],
        [5., 6., -inf, -inf]])

the mask change the value in unwanted position to -inf, the value will become 0 after passing softmax

Causal mask

In [10]:
seq_len = 5
# diagonal = 0 : default
# diagonal > 0 (up to length) : shift to upper
# diagonal < 0 (up to length) : shift to lower
# diagonal: the step toward up/down 
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1) # torch.tril is lower triangular matrix
causal_mask

tensor([[[0., 1., 1., 1., 1.],
         [0., 0., 1., 1., 1.],
         [0., 0., 0., 1., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 0.]]])

In [11]:
# False: allow attention
# True: Masked(prevent future access)
causal_mask.bool()


tensor([[[False,  True,  True,  True,  True],
         [False, False,  True,  True,  True],
         [False, False, False,  True,  True],
         [False, False, False, False,  True],
         [False, False, False, False, False]]])

In [12]:
(causal_mask == 0).type(torch.int)

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

### $W_q \times Q$

In [52]:
batch_size = 2
seq_len = 5
d_model = 8  # Model embedding size
h = 2
d_k = d_model // h
q = torch.randn(batch_size, seq_len, d_model)
k = torch.randn(batch_size, seq_len, d_model)
v = torch.randn(batch_size, seq_len, d_model)

w_q = nn.Linear(d_model, d_model)
w_k = nn.Linear(d_model, d_model)
w_v = nn.Linear(d_model, d_model)

In [53]:
w_q

Linear(in_features=8, out_features=8, bias=True)

In [54]:
w_q.weight

Parameter containing:
tensor([[ 0.1725, -0.3349, -0.1234, -0.1965, -0.1648,  0.1016,  0.0430,  0.0636],
        [-0.1497, -0.1052, -0.3213,  0.3330,  0.2692, -0.0121, -0.1386,  0.0866],
        [-0.0665, -0.1916, -0.0689,  0.3433, -0.1171, -0.1061, -0.1027,  0.1022],
        [-0.0952, -0.0881,  0.1007,  0.2028, -0.0345,  0.1558, -0.3399, -0.3178],
        [-0.0326, -0.0659, -0.0958, -0.0571, -0.3104, -0.2467,  0.3229, -0.2918],
        [ 0.3287, -0.0809,  0.1528, -0.2151, -0.1976, -0.0709,  0.2346, -0.0394],
        [-0.2604, -0.2229,  0.3502, -0.1222,  0.0841, -0.2988, -0.3391,  0.0222],
        [-0.3278, -0.2860, -0.0623, -0.2128,  0.2085, -0.1262,  0.0303, -0.3206]],
       requires_grad=True)

In [55]:
w_q.bias

Parameter containing:
tensor([ 0.2998, -0.0377,  0.0533, -0.1341, -0.1464,  0.2658,  0.2902,  0.3178],
       requires_grad=True)

In [56]:
q

tensor([[[-0.5235,  1.0046, -1.7567, -0.9155, -0.3476,  1.5067,  1.5777,
           0.5178],
         [ 0.0852, -0.0361,  1.3978, -0.2881,  1.2564, -0.6577, -0.2225,
          -0.4758],
         [-0.8826,  0.1328, -0.1501, -0.8849, -0.5831, -0.6050, -0.6082,
           1.2217],
         [-0.0983, -0.5606,  1.0783,  2.4776,  1.4231, -1.6117,  0.6679,
          -0.0258],
         [-1.0718, -1.7601, -0.6874, -0.9611,  1.0130, -0.4155,  2.1231,
           0.2980]],

        [[-1.0091,  1.0115, -0.7801, -0.2126,  0.4783,  1.0585,  0.6611,
           1.4349],
         [ 2.3659,  0.2244,  1.1176,  0.6590, -0.4338, -0.6494,  0.7721,
          -1.6527],
         [ 0.5162,  0.4680, -2.1609, -0.5484, -0.2649, -1.6963, -0.2651,
          -0.9882],
         [-0.9993, -0.9777, -2.2083,  0.4416,  0.6509, -1.2840,  1.1547,
           0.5408],
         [ 2.1088, -0.7736, -0.4159, -0.9555,  1.2482,  0.7222,  0.9700,
           1.3866]]])

In [57]:
w_q(q)

tensor([[[ 5.8082e-01, -9.0997e-02, -5.2589e-01, -9.8945e-01,  1.1944e-01,
           2.5246e-01, -1.3038e+00,  1.2532e-01],
         [-1.0295e-01, -2.5597e-01, -2.4384e-01,  2.4362e-02, -4.2495e-01,
           3.3734e-01,  1.1679e+00,  7.6521e-01],
         [ 3.8163e-01, -1.2559e-01,  1.1287e-01, -5.1200e-01, -2.8421e-01,
           9.9676e-02,  9.1111e-01,  3.1137e-01],
         [-5.2050e-01,  8.2216e-01,  8.7650e-01,  1.6614e-02, -1.7179e-01,
          -9.8481e-02,  8.8974e-01,  4.4470e-01],
         [ 8.7899e-01,  2.1805e-01, -8.2876e-02, -1.0571e+00,  5.1197e-01,
           4.7323e-01,  3.3434e-01,  1.6523e+00]],

        [[ 7.3410e-02,  3.3545e-01, -1.8223e-01, -7.8119e-01, -7.0820e-01,
          -2.9223e-01, -3.8831e-01, -2.0813e-02],
         [ 2.9909e-01, -9.1436e-01, -1.2630e-01,  4.3661e-02,  6.4358e-01,
           1.4324e+00, -2.0592e-01, -1.8702e-01],
         [ 4.0360e-01,  2.4773e-01,  2.7218e-02, -4.0428e-01,  7.4775e-01,
           3.3475e-01, -8.5667e-02,  7.3348e-01]

In [58]:
# w_q(q) equals to q * w_q.wieght + bias
assert torch.allclose(w_q(q), torch.matmul(q, w_q.weight.T) + w_q.bias), "w_q(q) doesn't equl to q*w_q^T + bias"

In [59]:
# assert torch.allclose(w_q(q), q @ w_q.weight.T), 'they are different'

In [60]:
# If w = nn.Linear(d_model, d_model, bias=False) then they will be the same
w_test = nn.Linear(d_model, d_model, bias=False)
assert torch.allclose(w_test(q), q @ w_test.weight.T), 'they are different'

In [61]:
query = w_q(q)
key = w_k(k)
value = w_v(v)
query.shape

torch.Size([2, 5, 8])

In [62]:
# keep the batch size and seq_len, decompose the matrix into smaller matrix
# so we can give each small matrix different head
# later, we can perform independent attention calculations for each head
query.view(query.shape[0], query.shape[1], h, d_k).shape

torch.Size([2, 5, 2, 4])

In [63]:
"""
The reason for using (batch_size, h, seq_len, d_k) instead of (batch_size, seq_len, h, d_k) is that:

The attention mechanism operates independently across heads.
Each head will perform self-attention on its own set of d_k-dimensional vectors.
The typical implementation of multi-head attention expects the shape (batch_size, h, seq_len, d_k).
When performing matrix multiplications (like query @ key.T), we want to apply attention per head.
This format is easier for batched computations in PyTorch and TensorFlow.
"""

query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2).shape

torch.Size([2, 2, 5, 4])

In [64]:
query = query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2)
key = key.view(key.shape[0], key.shape[1], h, d_k).transpose(1, 2)
value = value.view(value.shape[0], value.shape[1], h, d_k).transpose(1, 2)


In [65]:
query.transpose(-2, -1)

tensor([[[[ 5.8082e-01, -1.0295e-01,  3.8163e-01, -5.2050e-01,  8.7899e-01],
          [-9.0997e-02, -2.5597e-01, -1.2559e-01,  8.2216e-01,  2.1805e-01],
          [-5.2589e-01, -2.4384e-01,  1.1287e-01,  8.7650e-01, -8.2876e-02],
          [-9.8945e-01,  2.4362e-02, -5.1200e-01,  1.6614e-02, -1.0571e+00]],

         [[ 1.1944e-01, -4.2495e-01, -2.8421e-01, -1.7179e-01,  5.1197e-01],
          [ 2.5246e-01,  3.3734e-01,  9.9676e-02, -9.8481e-02,  4.7323e-01],
          [-1.3038e+00,  1.1679e+00,  9.1111e-01,  8.8974e-01,  3.3434e-01],
          [ 1.2532e-01,  7.6521e-01,  3.1137e-01,  4.4470e-01,  1.6523e+00]]],


        [[[ 7.3410e-02,  2.9909e-01,  4.0360e-01,  4.8679e-01,  1.1593e+00],
          [ 3.3545e-01, -9.1436e-01,  2.4773e-01,  1.1488e+00, -1.4366e-01],
          [-1.8223e-01, -1.2630e-01,  2.7218e-02,  6.0752e-01, -4.1862e-01],
          [-7.8119e-01,  4.3661e-02, -4.0428e-01, -8.7257e-01, -1.2033e+00]],

         [[-7.0820e-01,  6.4358e-01,  7.4775e-01,  4.6677e-01, -7.26

In [66]:
attention_score = (query @ key.transpose(-2 ,-1)) / math.sqrt(d_k)
attention_score

tensor([[[[-0.7203, -0.3064,  0.4109,  0.0666, -0.1609],
          [-0.1691,  0.0144,  0.0799,  0.0180, -0.0891],
          [-0.3267, -0.0824,  0.0505,  0.0658, -0.1116],
          [ 0.7380,  0.1746, -0.3156, -0.1843,  0.2521],
          [-0.5215, -0.3346,  0.2616,  0.0733, -0.0519]],

         [[ 0.0248,  0.4642,  0.0299,  0.0727,  0.1342],
          [-0.3030, -0.2166,  0.3387,  0.3365,  0.2946],
          [-0.1177, -0.2484,  0.1473,  0.1265,  0.1060],
          [-0.2052, -0.3469,  0.1523,  0.1412,  0.0807],
          [-1.0858,  0.4589,  0.6272,  0.8261,  0.4979]]],


        [[[-0.0701, -0.1955, -0.1165, -0.1708,  0.0830],
          [ 0.1233, -0.0567, -0.3200, -0.1809, -0.0901],
          [ 0.0708, -0.2932, -0.2034, -0.0876,  0.1254],
          [ 0.0525, -0.8598, -0.4889,  0.0127,  0.2267],
          [ 0.2080, -0.5737, -0.5914, -0.4694,  0.2601]],

         [[-0.3492,  0.8303,  0.8058,  0.3499,  0.1072],
          [ 0.3669, -0.6335, -0.4048, -0.2592, -0.4588],
          [ 0.3281, -0.

### Dropout

In [67]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply dropout with probability p = 0.5
dropout_output = numpy_dropout(x, p=0.5)

print("Input Tensor:\n", x)
print("Dropout Applied:\n", dropout_output)


Input Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Applied:
 [[ 0.  0.  6.]
 [ 0. 10. 12.]]


### Divide by 1-p for maintaining the expectation

test this by multiple runs as follows, we can see the value is nearly the same

In [68]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute expectation of the input
expected_input = np.mean(x)

# Run dropout multiple times and compute mean expectation
num_trials = 10000
expected_dropout_values = [np.mean(numpy_dropout(x, p=0.5)) for _ in range(num_trials)]

# Compute the overall expectation across trials
expected_dropout = np.mean(expected_dropout_values)

print("Expected Value of Input Tensor:", expected_input)
print("Expected Value After Dropout (Averaged over {} runs): {:.4f}".format(num_trials, expected_dropout))


Expected Value of Input Tensor: 3.5
Expected Value After Dropout (Averaged over 10000 runs): 3.5052


In [69]:

def numpy_bernoulli(probabilities):
    """Simulates torch.bernoulli using NumPy."""
    return np.random.binomial(n=3, p=probabilities)

# Example probability tensor (same as in PyTorch example)
probabilities = np.array([0.1, 0.5, 0.9])

# Generate Bernoulli samples
samples = numpy_bernoulli(probabilities)

print("Probabilities:", probabilities)
print("Bernoulli Samples:", samples)


Probabilities: [0.1 0.5 0.9]
Bernoulli Samples: [2 1 3]


## Tokenizers

In [70]:
from tokenizers import Tokenizer, models, trainers, pre_tokenizers
from tokenizers.normalizers import Lowercase
from tokenizers.pre_tokenizers import Whitespace
import pandas as pd

# Sample corpus
corpus = [
    "Hello world!",
    "Hello ChatGPT!",
    "This is a test sentence.",
    "Hello, this is another test.",
    "Test your tokenizer with a sample text.",
    "Banana, banana, BANANA"
]

# Initialize a WordLevel tokenizer
tokenizer = Tokenizer(models.WordLevel(unk_token="[UNK]"))

# Set normalization (lowercasing)
tokenizer.normalizer = Lowercase()

# Set pre-tokenizer (whitespace splitting)
tokenizer.pre_tokenizer = Whitespace()

# Trainer with min_frequency=2
trainer = trainers.WordLevelTrainer(
    min_frequency=2,
    special_tokens=["[UNK]", "[PAD]", "[SOS]", "[EOS]"]
)

# Train tokenizer
tokenizer.train_from_iterator(corpus, trainer)

# Get the vocabulary
vocab = tokenizer.get_vocab()

# Convert to DataFrame for better readability
vocab_df = pd.DataFrame(vocab.items(), columns=["Token", "ID"])

# Print the vocabulary
print(vocab_df)


     Token  ID
0        a  10
1    [UNK]   0
2       is  11
3    [EOS]   3
4        ,   4
5     this  12
6     test   8
7        .   5
8        !   9
9    [PAD]   1
10  banana   6
11   hello   7
12   [SOS]   2


In [71]:
tokenized_corpus = [tokenizer.encode(sentence).tokens for sentence in corpus]
tokenized_corpus

[['hello', '[UNK]', '!'],
 ['hello', '[UNK]', '!'],
 ['this', 'is', 'a', 'test', '[UNK]', '.'],
 ['hello', ',', 'this', 'is', '[UNK]', 'test', '.'],
 ['test', '[UNK]', '[UNK]', '[UNK]', 'a', '[UNK]', '[UNK]', '.'],
 ['banana', ',', 'banana', ',', 'banana']]

In [72]:
# Flatten the list of tokenized words
flat_tokenized_words = [word for sentence in tokenized_corpus for word in sentence]
flat_tokenized_words

['hello',
 '[UNK]',
 '!',
 'hello',
 '[UNK]',
 '!',
 'this',
 'is',
 'a',
 'test',
 '[UNK]',
 '.',
 'hello',
 ',',
 'this',
 'is',
 '[UNK]',
 'test',
 '.',
 'test',
 '[UNK]',
 '[UNK]',
 '[UNK]',
 'a',
 '[UNK]',
 '[UNK]',
 '.',
 'banana',
 ',',
 'banana',
 ',',
 'banana']

In [73]:
# Count the occurrences of each word in the vocabulary
word_counts = Counter(flat_tokenized_words)
word_count_df = pd.DataFrame(word_counts.items(), columns=["Token", "Count"])
word_count_df

Token  Count
0   hello      3
1   [UNK]      9
2       !      2
3    this      2
4      is      2
5       a      2
6    test      3
7       .      3
8       ,      3
9  banana      3

## torch.tensor.size()

In [74]:
# Define tokens
sos_token = torch.tensor([0])  # Start of Sequence <SOS>
eos_token = torch.tensor([1])  # End of Sequence <EOS>
pad_token = 2                  # Padding token

# Example encoded tokens
encoded_input_tokens = torch.tensor([101, 2009, 2003, 1037, 2204, 2154, 102])  # Main sequence
encoded_num_padding_tokens = 3  # Number of padding tokens

# Construct the encoded input using torch.cat()
encoded_input = torch.cat([
    sos_token,  
    encoded_input_tokens,  
    eos_token,  
    torch.tensor([pad_token] * encoded_num_padding_tokens, dtype=torch.int64)
])
encoded_input

tensor([   0,  101, 2009, 2003, 1037, 2204, 2154,  102,    1,    2,    2,    2])

In [75]:
encoded_input.size(0)

12

## encoder_mask

In [76]:
(encoded_input != pad_token).unsqueeze(0).unsqueeze(0).int()

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]], dtype=torch.int32)

## decoder_mask

In [77]:
"""
a is decoded_input, so there is no eos
"""
decoder_input = torch.tensor([0, 12, 13, 2 , 2]) # the real input is 2: 0 is SOS, 2 is pad
# b = torch.tensor([2])
(decoder_input != pad_token).int() # False = 1: means the input rather thant pad token

tensor([1, 1, 1, 0, 0], dtype=torch.int32)

In [78]:
# Build causal_mask with torch.ones
causal_mask = torch.triu(torch.ones(1, seq_len, seq_len), diagonal=1)

# Use '&' to make the causal mask align with the length of the input sentence
(decoder_input != pad_token).int() & (causal_mask == 0).type(torch.int) # Convert the 1 to 0, 0 to 1: align with the (a != b).int(), 1 means the real input

tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 0, 0]]], dtype=torch.int32)

## Dataloader check

In [80]:
class ToyDataset(Dataset):
    def __init__(self, num_samples=5, seq_len=6, pad_token=0):
        self.num_samples = num_samples
        self.seq_len = seq_len
        self.pad_token = pad_token
        
        # Fake tokenized sentences with different lengths
        self.data = [
            [101, 7592, 2088, 102],  # "Hello world"
            [2054, 2024, 2017, 102],  # "How are you?"
            [1045, 2572, 2986, 102],  # "I am fine"
            [2748, 102],  # "Yes"
            [2204, 2872, 102]  # "Good morning"
        ]
        
        # Padding each sequence to `seq_len`
        for i in range(len(self.data)):
            self.data[i] += [self.pad_token] * (self.seq_len - len(self.data[i]))  # Padding
        
    def __len__(self):
        return self.num_samples
    
    def __getitem__(self, idx):
        # Simulated encoder input (source sentence) and decoder input (target sentence)
        encoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        decoded_input = torch.tensor(self.data[idx], dtype=torch.int64)  # (seq_len)
        
        # Create masks
        encoder_mask = (encoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int()  # (1, 1, seq_len)
        decoder_mask = (decoded_input != self.pad_token).unsqueeze(0).unsqueeze(0).int() & self.causal_mask(decoded_input.size(0))  # (1, seq_len, seq_len)
        
        return {
            "encoder_input": encoded_input,  # (seq_len)
            "decoder_input": decoded_input,  # (seq_len)
            "encoder_mask": encoder_mask,  # (1, 1, seq_len)
            "decoder_mask": decoder_mask,  # (1, seq_len, seq_len)
            "label": decoded_input,  # (seq_len)
        }
    
    def causal_mask(self, size):
        """ Generate a causal mask for the decoder to prevent attending future tokens """
        mask = torch.tril(torch.ones((size, size), dtype=torch.int))  # Lower triangular matrix
        return mask.unsqueeze(0)  # (1, seq_len, seq_len)
