In [11]:
import torch
import torch.nn as nn
import math
import numpy as np

In [38]:
torch.tensor(10)

tensor(10)

In [39]:
d_model = 512
torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

tensor([1.0000e+00, 1.0366e+00, 1.0746e+00, 1.1140e+00, 1.1548e+00, 1.1971e+00,
        1.2409e+00, 1.2864e+00, 1.3335e+00, 1.3824e+00, 1.4330e+00, 1.4855e+00,
        1.5399e+00, 1.5963e+00, 1.6548e+00, 1.7154e+00, 1.7783e+00, 1.8434e+00,
        1.9110e+00, 1.9810e+00, 2.0535e+00, 2.1288e+00, 2.2067e+00, 2.2876e+00,
        2.3714e+00, 2.4582e+00, 2.5483e+00, 2.6416e+00, 2.7384e+00, 2.8387e+00,
        2.9427e+00, 3.0505e+00, 3.1623e+00, 3.2781e+00, 3.3982e+00, 3.5227e+00,
        3.6517e+00, 3.7855e+00, 3.9242e+00, 4.0679e+00, 4.2170e+00, 4.3714e+00,
        4.5316e+00, 4.6976e+00, 4.8697e+00, 5.0481e+00, 5.2330e+00, 5.4247e+00,
        5.6234e+00, 5.8294e+00, 6.0430e+00, 6.2643e+00, 6.4938e+00, 6.7317e+00,
        6.9783e+00, 7.2339e+00, 7.4989e+00, 7.7737e+00, 8.0584e+00, 8.3536e+00,
        8.6596e+00, 8.9769e+00, 9.3057e+00, 9.6466e+00, 1.0000e+01, 1.0366e+01,
        1.0746e+01, 1.1140e+01, 1.1548e+01, 1.1971e+01, 1.2409e+01, 1.2864e+01,
        1.3335e+01, 1.3824e+01, 1.4330e+

In [40]:
torch.arange(0, d_model, 2).float()

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [41]:
torch.arange(1, d_model, 2).float()

tensor([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,  23.,
         25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,  45.,  47.,
         49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,  67.,  69.,  71.,
         73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,  89.,  91.,  93.,  95.,
         97.,  99., 101., 103., 105., 107., 109., 111., 113., 115., 117., 119.,
        121., 123., 125., 127., 129., 131., 133., 135., 137., 139., 141., 143.,
        145., 147., 149., 151., 153., 155., 157., 159., 161., 163., 165., 167.,
        169., 171., 173., 175., 177., 179., 181., 183., 185., 187., 189., 191.,
        193., 195., 197., 199., 201., 203., 205., 207., 209., 211., 213., 215.,
        217., 219., 221., 223., 225., 227., 229., 231., 233., 235., 237., 239.,
        241., 243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
        265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285., 287.,
        289., 291., 293., 295., 297., 29

In [42]:
d_model = 512

# Using torch.exp
exp_values = torch.exp(torch.arange(0, d_model, 2).float() * (math.log(10000.0) / d_model))

# Using torch.pow
pow_values = torch.pow(torch.tensor(10000.0), torch.arange(0, d_model, 2).float() / d_model)

# Check if both are the same
print(torch.allclose(exp_values, pow_values))  # Should be True


True


In [43]:
512 // 64

8

In [44]:
512/64

8.0

### Mask in Transfomer

Pad mask

In [45]:
atten_scores = torch.tensor([[1, 2, 3, 4],
                            [5, 6, 7, 8]]).float()

pad_mask = torch.tensor([[1, 1, 1, 0],
                         [1, 1, 0, 0]])
atten_scores.masked_fill(pad_mask == 0, float('-inf'))

tensor([[1., 2., 3., -inf],
        [5., 6., -inf, -inf]])

the mask change the value in unwanted position to -inf, the value will become 0 after passing softmax

Causal mask

In [46]:
seq_len = 5
# diagonal = 0 : default
# diagonal > 0 (upper to length) : shift to upper
# diagonal < 0 (upper to length) : shift to lower
causal_mask = torch.triu(torch.ones(seq_len, seq_len), diagonal=1) # torch.tril is lower triangular matrix
causal_mask

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])

In [47]:
# False: allow attention
# True: Masked(prevent future access)
causal_mask.bool()


tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

### $W_q \times Q$

In [95]:
batch_size = 2
seq_len = 4
d_model = 8  # Model embedding size
h = 2
d_k = d_model // h
q = torch.randn(batch_size, seq_len, d_model)
k = torch.randn(batch_size, seq_len, d_model)
v = torch.randn(batch_size, seq_len, d_model)

w_q = nn.Linear(d_model, d_model)
w_k = nn.Linear(d_model, d_model)
w_v = nn.Linear(d_model, d_model)

In [72]:
w_q

Linear(in_features=8, out_features=8, bias=True)

In [73]:
w_q.weight

Parameter containing:
tensor([[ 0.2111, -0.1161,  0.1885, -0.0730,  0.2030, -0.3014,  0.0864,  0.0759],
        [ 0.1219, -0.1910,  0.1038,  0.0461,  0.3176,  0.0714, -0.2393,  0.0059],
        [-0.0884,  0.2548,  0.0199, -0.2067,  0.1611,  0.2984,  0.1323,  0.2228],
        [-0.3201,  0.0113, -0.0106, -0.1457, -0.2766, -0.1569, -0.3010,  0.0380],
        [ 0.1460, -0.2015, -0.0079,  0.0074,  0.2680,  0.3047,  0.2166,  0.1411],
        [-0.2245,  0.2185,  0.2517,  0.1320,  0.2007,  0.2198,  0.0316, -0.1587],
        [ 0.2890, -0.2662, -0.1288, -0.1369, -0.2060,  0.3290, -0.2989,  0.0451],
        [-0.2206,  0.2229,  0.2288,  0.2423, -0.2317,  0.1357, -0.0972,  0.2270]],
       requires_grad=True)

In [74]:
w_q.bias

Parameter containing:
tensor([ 0.0154, -0.3341,  0.2655,  0.2718,  0.2809, -0.3188, -0.0718, -0.2876],
       requires_grad=True)

In [75]:
q

tensor([[[ 0.7132, -0.2739, -0.4353, -1.6998, -0.0278, -1.7315, -0.0546,
          -1.1710],
         [ 1.5169, -0.9338, -0.2130, -0.0695,  0.2930,  0.2094,  0.9007,
          -0.6683],
         [-0.2447,  0.2697,  0.7474,  0.6196, -0.4493,  0.6622, -0.4022,
          -0.7072],
         [ 0.1573, -0.6627, -2.5437, -0.2119,  1.9522,  0.7903, -0.0467,
           0.0662]],

        [[ 0.7824, -0.2996,  0.8681,  0.1862,  0.2521, -0.7392,  0.7083,
          -0.1551],
         [ 1.0007,  0.7010,  1.1217,  1.3078,  0.3737, -0.0953,  0.0075,
          -0.3924],
         [ 0.6895, -1.0957, -0.9057, -0.2559, -0.9743,  0.2925, -1.4120,
          -0.0476],
         [-1.5162,  0.6263,  0.9453,  0.1660,  1.5419, -2.1466, -0.0731,
          -3.0045]]])

In [110]:
w_q(q)

tensor([[[-0.4601, -0.2618,  0.2760, -0.0117,  0.1811,  0.7136, -0.6927,
           0.5770],
         [ 0.4142,  1.0766, -1.0255,  0.2859,  0.1066,  0.4603,  0.7750,
          -0.8607],
         [ 0.4098,  0.5577,  0.1919, -0.0599,  0.5664,  0.7690, -0.1441,
          -0.3678],
         [ 0.4016, -0.2982,  0.2070,  0.1092, -0.5403,  1.0988, -0.0518,
          -0.4172]],

        [[ 0.1227, -0.8128,  0.0164,  0.5537, -0.7277,  0.7686,  0.0435,
           0.2968],
         [ 0.9401,  0.0824,  0.0732,  0.3911,  0.8812, -0.0277,  0.2050,
           0.1086],
         [ 1.5102,  0.2171, -0.3944,  0.9532, -0.2193,  0.5461,  1.1265,
           0.7569],
         [ 0.5780,  0.2778, -0.2590, -0.0228, -0.1115,  0.3983,  0.7533,
           0.2462]]], grad_fn=<ViewBackward0>)

In [112]:
# w_q(q) equals to q * w_q.wieght + bias
assert torch.allclose(w_q(q), torch.matmul(q, w_q.weight.T) + w_q.bias), "w_q(q) doesn't equl to q*w_q^T + bias"

In [122]:
assert torch.allclose(w_q(q), q @ w_q.weight.T), 'they are different'

AssertionError: they are different

In [121]:
# If w = nn.Linear(d_model, d_model, bias=False) then they will be the same
w_test = nn.Linear(d_model, d_model, bias=False)
assert torch.allclose(w_test(q), q @ w_test.weight.T), 'they are different'

In [101]:
query = w_q(q)
key = w_k(k)
value = w_v(v)
query.shape

torch.Size([2, 4, 8])

In [102]:
# keep the batch size and seq_len, decompose the matrix into smaller matrix
# so we can give each small matrix different head
# later, we can perform independent attention calculations for each head
query.view(query.shape[0], query.shape[1], h, d_k).shape

torch.Size([2, 4, 2, 4])

In [103]:
"""
The reason for using (batch_size, h, seq_len, d_k) instead of (batch_size, seq_len, h, d_k) is that:

The attention mechanism operates independently across heads.
Each head will perform self-attention on its own set of d_k-dimensional vectors.
The typical implementation of multi-head attention expects the shape (batch_size, h, seq_len, d_k).
When performing matrix multiplications (like query @ key.T), we want to apply attention per head.
This format is easier for batched computations in PyTorch and TensorFlow.
"""

query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2).shape

torch.Size([2, 2, 4, 4])

In [104]:
query = query.view(query.shape[0], query.shape[1], h, d_k).transpose(1, 2)
key = key.view(key.shape[0], key.shape[1], h, d_k).transpose(1, 2)
value = value.view(value.shape[0], value.shape[1], h, d_k).transpose(1, 2)


In [105]:
query.transpose(-2, -1)

tensor([[[[-0.4601,  0.4142,  0.4098,  0.4016],
          [-0.2618,  1.0766,  0.5577, -0.2982],
          [ 0.2760, -1.0255,  0.1919,  0.2070],
          [-0.0117,  0.2859, -0.0599,  0.1092]],

         [[ 0.1811,  0.1066,  0.5664, -0.5403],
          [ 0.7136,  0.4603,  0.7690,  1.0988],
          [-0.6927,  0.7750, -0.1441, -0.0518],
          [ 0.5770, -0.8607, -0.3678, -0.4172]]],


        [[[ 0.1227,  0.9401,  1.5102,  0.5780],
          [-0.8128,  0.0824,  0.2171,  0.2778],
          [ 0.0164,  0.0732, -0.3944, -0.2590],
          [ 0.5537,  0.3911,  0.9532, -0.0228]],

         [[-0.7277,  0.8812, -0.2193, -0.1115],
          [ 0.7686, -0.0277,  0.5461,  0.3983],
          [ 0.0435,  0.2050,  1.1265,  0.7533],
          [ 0.2968,  0.1086,  0.7569,  0.2462]]]],
       grad_fn=<TransposeBackward0>)

In [106]:
attention_score = (query @ key.transpose(-2 ,-1)) / math.sqrt(d_k)
attention_score

tensor([[[[ 0.0890,  0.0380,  0.1451,  0.0384],
          [-0.2554, -0.2696, -0.3594, -0.3541],
          [ 0.0490,  0.1333, -0.0733, -0.1779],
          [ 0.0635,  0.1299, -0.0178,  0.3031]],

         [[ 0.0316, -0.3110,  0.0640,  0.2993],
          [ 0.3691,  0.3426, -0.1249,  0.1919],
          [ 0.4070,  0.1153,  0.1259,  0.2641],
          [-0.0034, -0.1989, -0.5468,  0.4380]]],


        [[[-0.0040,  0.2876,  0.2494,  0.2321],
          [-0.1905, -0.3061,  0.0460,  0.0161],
          [-0.3534, -0.5675, -0.0960,  0.0213],
          [-0.2530, -0.3804, -0.1190, -0.1752]],

         [[-0.3690, -0.5342, -0.0820, -0.2274],
          [ 0.4662,  0.2550,  0.1954,  0.3145],
          [-0.0350, -0.7330,  0.2087, -0.0320],
          [ 0.1691, -0.3480,  0.1701,  0.0909]]]], grad_fn=<DivBackward0>)

### Dropout

In [17]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Apply dropout with probability p = 0.5
dropout_output = numpy_dropout(x, p=0.5)

print("Input Tensor:\n", x)
print("Dropout Applied:\n", dropout_output)


Input Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Applied:
 [[2. 0. 6.]
 [0. 0. 0.]]


### Divide by 1-p for maintaining the expectation

test this by multiple runs as follows, we can see the value is nearly the same

In [21]:
def numpy_dropout(x, p=0.5):
    """Applies dropout using NumPy with probability p"""
    keep_prob = 1 - p
    mask = np.random.binomial(n=1, p=keep_prob, size=x.shape)  # Create Bernoulli mask
    return (x * mask) / keep_prob  # Scale to maintain expectation

# Example input matrix
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

# Compute expectation of the input
expected_input = np.mean(x)

# Run dropout multiple times and compute mean expectation
num_trials = 10000
expected_dropout_values = [np.mean(numpy_dropout(x, p=0.5)) for _ in range(num_trials)]

# Compute the overall expectation across trials
expected_dropout = np.mean(expected_dropout_values)

print("Expected Value of Input Tensor:", expected_input)
print("Expected Value After Dropout (Averaged over {} runs): {:.4f}".format(num_trials, expected_dropout))


Expected Value of Input Tensor: 3.5
Expected Value After Dropout (Averaged over 10000 runs): 3.4921


In [10]:

def numpy_bernoulli(probabilities):
    """Simulates torch.bernoulli using NumPy."""
    return np.random.binomial(n=3, p=probabilities)

# Example probability tensor (same as in PyTorch example)
probabilities = np.array([0.1, 0.5, 0.9])

# Generate Bernoulli samples
samples = numpy_bernoulli(probabilities)

print("Probabilities:", probabilities)
print("Bernoulli Samples:", samples)


Probabilities: [0.1 0.5 0.9]
Bernoulli Samples: [0 2 3]
